"""Add session_status to customer

Revision ID: c074860fcb89
Revises: f33fc726a86f
Create Date: 2026-08-19 12:03:25.316403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c074860fcb89'
down_revision: Union[str, None] = 'f33fc726a86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('session_status', sa.String(), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'session_status')
    # ### end Alembic commands ###
