"""Add audit and security alerts

Revision ID: f33fc726a86f
Revises: f80818ba0aa5
Create Date: 2026-08-19 11:50:04.672550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33fc726a86f'
down_revision: Union[str, None] = 'f80818ba0aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.Enum('HUMAN', 'AGENT', name='actortype', native_enum=False, length=20), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('original_prompt', sa.String(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decision', sa.Enum('PENDING', 'ALLOWED', 'BLOCKED', name='auditdecision', native_enum=False, length=20), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_agent_id'), 'audit_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_customer_id'), 'audit_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_operation'), 'audit_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='alertstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_agent_id'), 'security_alerts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_session_id'), 'security_alerts', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_user_id'), 'security_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_alerts_user_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_session_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_agent_id'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operation'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_customer_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
